# Path inputs & analysis frame
scan_path: /Users/davidspector/Home/Stanford/QuantUS Projects/Sample Data/Canon IQ/Sample Patient 001/Preset_2/image.bin
phantom_path: /Users/davidspector/Home/Stanford/QuantUS Projects/Sample Data/Canon IQ/Phantom data/Preset_2/phantom2.bin
roi_path: /Users/davidspector/Home/Stanford/QuantUS Projects/Sample Data/Canon IQ/Sample Patient 001/Preset_2/roi.pkl
analysis_config_path: /Users/davidspector/Home/Stanford/QuantUS Projects/Sample Data/Canon IQ/Sample Patient 001/Preset_2/analysisConfig.pkl

# Data Loading Customization
parser: canon_iq
parser_output_path: parsed_data.pkl
roi_loader: pkl_roi
analysis_config_loader: pkl_config
save_parsed_results: False

# Analysis Customization
analysis_class: abn
analysis_kwargs:
  refAttenuation: 0.5
  refBackScatterCoef: 0.5
analysis_output_path: analysis_results.pkl
save_analysis_results: False

# Visualization Customization
visualization_class: paramaps
visualization_computation_kwargs:
visualization_export_kwargs:
  psPlotOutputPath: psPlot.png
  paramapFolderPath: z-paramaps
export_visualizations: True
visualization_output_path: visualization_results.pkl
save_visualization_class: False
