# Path inputs & analysis frame
scan_path: /Volumes/TOSHIBA EXT/Philips 3D RF/Scans/SHC-P004-V03-RF1_20241015_155205.rf
phantom_path: /Volumes/TOSHIBA EXT/Philips 3D RF/Phantom/IMAN-PHANTOM-RF2_20250311_162604.rf
seg_path: /Volumes/TOSHIBA EXT/Philips 3D RF/Segmentations/SHC-P004-V03-RF1_20241015_155205_segmentation.nii.gz
config_path: 

# Core Pipeline Customization
scan_loader: philips_rf_sc_3d
analysis_type: spectral_paramap_sc_3d
visualization_type: paramap_drawing_sc_3d

# Data Loading Customization
scan_loader_kwargs:
parser_output_path: parsed_data.pkl
seg_loader: nifti_voi
seg_loader_kwargs:
  assert_scan: True
  assert_phantom: False
config_loader: philips_3d_config
config_kwargs:
  assert_scan: False
  assert_phantom: False
save_parsed_results: False

# Analysis Customization
analysis_kwargs:
analysis_output_path: analysis_results.pkl
save_analysis_results: False

# Visualization Customization
visualization_kwargs:
  ps_plot_output_path: psPlot.png
  paramap_folder_path: z-paramaps
export_visualizations: True
visualization_output_path: visualization_results.pkl
save_visualization_class: False

# Data Export Customization
data_export_type: mean_paramap_vals
data_export_path: test.csv
data_export_kwargs: